// Açılır pencerelerin gösterileceği sayfalar (panelde listeden seçilir).
// Yeni sayfa eklenince buraya da eklenmeli (sitemap.xml de bu listeden üretilir); '/blog/*' tüm blog yazılarını kapsar.
export const SITE_PAGES = [
  { label: 'Ana sayfa (/)', value: '/' },
  { label: 'Online Ön Muhasebe Programı Fiyatları (/fiyatlar)', value: '/fiyatlar' },
  { label: 'KolayBi Ofis: KOBİ’ler için Web Tabanlı Ön Muhasebe ve e-Fatura (/kolay-on-muhasebe-programi)', value: '/kolay-on-muhasebe-programi' },
  { label: 'Yıllık 5.000 ₺ ile e-Faturaya Geçin (/kolaybi-jet)', value: '/kolaybi-jet' },
  { label: 'KolayBi Banka (/online-banka-entegrasyonu)', value: '/online-banka-entegrasyonu' },
  { label: 'Mali Müşavirler için Mükellef Takip Platformu (/bilink)', value: '/bilink' },
  { label: 'AI Ön Muhasebe: Yazarak veya Konuşarak Yönetin (/ai-muhasebe)', value: '/ai-muhasebe' },
  { label: 'e-Faturaya Ücretsiz Geçiş (/kolaybi-e-faturam)', value: '/kolaybi-e-faturam' },
  { label: 'Bizimle İletişime Geçin (/iletisim)', value: '/iletisim' },
  { label: 'Cari Hesap Takip Programı (/cari-hesap-programi)', value: '/cari-hesap-programi' },
  { label: 'Davet Et Kazan Kampanyası (/kampanyalar/davet-et-kazan)', value: '/kampanyalar/davet-et-kazan' },
  { label: 'Fatura Kesme Programı (/fatura-kesme-programi)', value: '/fatura-kesme-programi' },
  { label: 'Gelir Gider Takip Programı (/gelir-gider-takip-programi)', value: '/gelir-gider-takip-programi' },
  { label: 'KolayBi Kullanım Videoları: Fatura, Cari, Rapor (/kullanim-videolari)', value: '/kullanim-videolari' },
  { label: 'KolayBi Link Başvuru Formu (/kolaybi-bilink-formu)', value: '/kolaybi-bilink-formu' },
  { label: 'KolayBi’ye Geçiş: e-Fatura, Stok ve Cari Aktarımı (/kolaybiye-gecis)', value: '/kolaybiye-gecis' },
  { label: 'Kullanıcılarımız ve Hakkımızdaki Görüşleri (/referanslar)', value: '/referanslar' },
  { label: 'Muhasebe ve Finans Blogu (/blog)', value: '/blog' },
  { label: 'Proje Gelir Gider Takibi (/proje-gelir-gider-takibi)', value: '/proje-gelir-gider-takibi' },
  { label: 'QNB Dijital Köprü Kampanyası (/kampanyalar/qnb-dijital-kopru)', value: '/kampanyalar/qnb-dijital-kopru' },
  { label: 'Sanal POS ile Online Tahsilat (/sanal-pos-entegrasyonu)', value: '/sanal-pos-entegrasyonu' },
  { label: 'Sipariş Takip Programı (/siparis-takip-programi)', value: '/siparis-takip-programi' },
  { label: 'Stok Takip Programı (/stok-takip-programi)', value: '/stok-takip-programi' },
  { label: 'Sıkça Sorulan Sorular (/sikca-sorulan-sorular)', value: '/sikca-sorulan-sorular' },
  { label: 'e-Arşiv Fatura Programı (/e-arsiv)', value: '/e-arsiv' },
  { label: 'e-Fatura Programı (/e-fatura)', value: '/e-fatura' },
  { label: 'e-SMM Programı (/e-smm-programi)', value: '/e-smm-programi' },
  { label: 'e-Ticaret ve Pazaryeri Entegrasyonu (/pazaryeri-entegrasyonu)', value: '/pazaryeri-entegrasyonu' },
  { label: 'e-İhracat Faturası Programı (/e-ihracat-programi)', value: '/e-ihracat-programi' },
  { label: 'e-İmza Programı (/e-imza-programi)', value: '/e-imza-programi' },
  { label: 'e-İrsaliye Programı (/e-irsaliye)', value: '/e-irsaliye' },
  { label: 'Ön Muhasebe Raporlama Programı (/on-muhasebe-raporlama-programi)', value: '/on-muhasebe-raporlama-programi' },
  { label: 'Gizlilik Politikası (/gizlilik-politikasi)', value: '/gizlilik-politikasi' },
  { label: 'Çerez Politikası (/cerez-politikasi)', value: '/cerez-politikasi' },
  { label: 'Cayma Hakkı Metni (/cayma-hakki-metni)', value: '/cayma-hakki-metni' },
  { label: 'Ticari Elektronik İleti Onay Metni (/ticari-elektronik-ileti)', value: '/ticari-elektronik-ileti' },
  { label: 'Kişisel Verilerin Korunması (/kisisel-verilerin-korunmasi)', value: '/kisisel-verilerin-korunmasi' },
  { label: 'Tüm blog yazıları (/blog/*)', value: '/blog/*' },
] as const
