/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    authors: Author;
    popups: Popup;
    analytics: Analytics;
    redirects: Redirect;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    popups: PopupsSelect<false> | PopupsSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Boş bırakırsanız başlıktan otomatik oluşur. /blog/ sonrası, örn. e-fatura-nedir
   */
  slug: string;
  /**
   * Boşsa metinden hesaplanır
   */
  readingMinutes?: number | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Boş bırakılırsa "Başlık | KolayBi" kullanılır
   */
  metaTitle?: string | null;
  /**
   * Google sonuçlarında görünen 150–160 karakterlik özet; liste kartında da kullanılır
   */
  description?: string | null;
  category: number | Category;
  author?: (number | null) | Author;
  /**
   * Boş bırakılırsa yazı listenin sonunda, tarihsiz görünür
   */
  publishedAt?: string | null;
  /**
   * İçerik güncellendiyse yazıda "Güncellendi" olarak görünür
   */
  contentUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görme engelli kullanıcılar ve Google için görselin kısa açıklaması
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cover?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Sitede görünen ad, örn. e-Fatura
   */
  title: string;
  /**
   * Filtre adresi, örn. e-fatura
   */
  slug: string;
  theme?: ('theme-ofis' | 'theme-jet' | 'theme-banka' | 'theme-link') | null;
  /**
   * Blog filtrelerindeki sırası
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Örn. İçerik Ekibi, Mali Müşavir
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sitede açılan duyuru ve kampanya ilanları. Aynı tasarımdan istediğiniz kadar ilan oluşturabilirsiniz. Bir sayfada aynı anda en fazla bir ilan gösterilir; birden çok ilan uyarsa önceliği yüksek olan çıkar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups".
 */
export interface Popup {
  id: number;
  name: string;
  active?: boolean | null;
  /**
   * Yüksek olan önce
   */
  priority?: number | null;
  design: 'klasik' | 'yan-gorsel' | 'kose' | 'serit' | 'tam-ekran' | 'yan-panel';
  theme: 'ofis' | 'jet' | 'lacivert' | 'acik';
  /**
   * Alt şerit ve köşe kartında küçük, diğerlerinde büyük gösterilir
   */
  image?: (number | null) | Media;
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  show: 'all' | 'include' | 'exclude';
  /**
   * “Tüm blog yazıları” her /blog/… sayfasını kapsar
   */
  pages?:
    | (
        | '/'
        | '/fiyatlar'
        | '/kolay-on-muhasebe-programi'
        | '/kolaybi-jet'
        | '/online-banka-entegrasyonu'
        | '/bilink'
        | '/ai-muhasebe'
        | '/kolaybi-e-faturam'
        | '/iletisim'
        | '/cari-hesap-programi'
        | '/kampanyalar/davet-et-kazan'
        | '/fatura-kesme-programi'
        | '/gelir-gider-takip-programi'
        | '/kullanim-videolari'
        | '/kolaybi-bilink-formu'
        | '/kolaybiye-gecis'
        | '/referanslar'
        | '/blog'
        | '/proje-gelir-gider-takibi'
        | '/kampanyalar/qnb-dijital-kopru'
        | '/sanal-pos-entegrasyonu'
        | '/siparis-takip-programi'
        | '/stok-takip-programi'
        | '/sikca-sorulan-sorular'
        | '/e-arsiv'
        | '/e-fatura'
        | '/e-smm-programi'
        | '/pazaryeri-entegrasyonu'
        | '/e-ihracat-programi'
        | '/e-imza-programi'
        | '/e-irsaliye'
        | '/on-muhasebe-raporlama-programi'
        | '/blog/*'
      )[]
    | null;
  /**
   * Listede olmayan adresler; * ile başlayanları kapsar (örn. /kampanyalar/*)
   */
  customPaths?: string[] | null;
  device?: ('all' | 'desktop' | 'mobile') | null;
  trigger?: ('delay' | 'scroll' | 'exit') | null;
  delay?: number | null;
  scroll?: number | null;
  frequency?: ('always' | 'session' | 'days') | null;
  days?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  bucket: string;
  day: string;
  kind: string;
  path: string;
  popup?: number | null;
  event: string;
  device: string;
  source?: string | null;
  label?: string | null;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eski ya da kırık bir adrese gelen ziyaretçiyi ve arama motorunu yeni adrese gönderir. Kaydettikten sonra en geç 1 dakika içinde geçerli olur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Tam adres de yapıştırabilirsiniz; alan adı ve sondaki / otomatik temizlenir.
   */
  from: string;
  to: string;
  type: '301' | '302';
  active?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Panele giriş yapabilen kişiler. "Seçili menüler" rolündeki kişi yalnızca işaretlediğiniz bölümleri görür ve düzenler.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Tam yetkili kişi kullanıcı ekleyip yetki verebilir.
   */
  role: 'admin' | 'editor';
  /**
   * İşaretlenen bölümler bu kişinin sol menüsünde görünür; işaretlenmeyenlere erişemez.
   */
  yetki?: {
    yazilar?: boolean | null;
    kategoriler?: boolean | null;
    yazarlar?: boolean | null;
    ilanlar?: boolean | null;
    analitik?: boolean | null;
    yonlendirmeler?: boolean | null;
    bulunamayan?: boolean | null;
    gorseller?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'popups';
        value: number | Popup;
      } | null)
    | ({
        relationTo: 'analytics';
        value: number | Analytics;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  readingMinutes?: T;
  cover?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  description?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  contentUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  theme?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups_select".
 */
export interface PopupsSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  priority?: T;
  design?: T;
  theme?: T;
  image?: T;
  eyebrow?: T;
  title?: T;
  text?: T;
  buttonText?: T;
  buttonLink?: T;
  show?: T;
  pages?: T;
  customPaths?: T;
  device?: T;
  trigger?: T;
  delay?: T;
  scroll?: T;
  frequency?: T;
  days?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  bucket?: T;
  day?: T;
  kind?: T;
  path?: T;
  popup?: T;
  event?: T;
  device?: T;
  source?: T;
  label?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  active?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cover?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  yetki?:
    | T
    | {
        yazilar?: T;
        kategoriler?: T;
        yazarlar?: T;
        ilanlar?: T;
        analitik?: T;
        yonlendirmeler?: T;
        bulunamayan?: T;
        gorseller?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  preset: 'deneme' | 'efatura' | 'jet' | 'banka' | 'ai' | 'link' | 'iletisim' | 'ozel';
  style: 'acik' | 'koyu' | 'kart';
  /**
   * Boşsa hazır CTA’nın rengi
   */
  theme?: ('ofis' | 'jet' | 'banka' | 'link') | null;
  /**
   * Vurgulamak istediğiniz kısmı *yıldız* arasına yazın
   */
  title?: string | null;
  text?: string | null;
  button?: string | null;
  link?: string | null;
  /**
   * Örn. "Kredi kartı istenmez, deneme sonunda otomatik ödeme alınmaz." Notu tamamen gizlemek için - yazın.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  text: string;
  link: string;
  variant: 'primary' | 'outline' | 'dark';
  align: 'left' | 'center';
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}